version: "3"

services:
  clickhouse:
    image: yandex/clickhouse-server
    expose:
      - 8123
      - 9000
    ports:
      - 9001:9000
      - 8123:8123
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/docker-entrypoint-initdb.d/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./.data/clickhouse/:/var/lib/clickhouse/

    healthcheck:
      # "clickhouse", "client", "-u ${CLICKHOUSE_USER}", "--password ${CLICKHOUSE_PASSWORD}", "-q 'SELECT 1'"
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "localhost:8123/ping"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
  # TODO
  # alertmanager:
  #   image: signoz/alertmanager:0.5.0
  #   volumes:
  #     - ./alertmanager.yml:/prometheus/alertmanager.yml
  #     - ./data/alertmanager:/data
  #   command:
  #     - '--config.file=/prometheus/alertmanager.yml'
  #     - '--storage.path=/data'
  #   ports:
  #     - 9093:9093
  query-service:
    image: signoz/query-service:0.5.0
    container_name: query-service
    command: [ "-config=/root/config/prometheus.yml" ]
    ports:
      - "9090:8080"
    volumes:
      - ./prometheus/prometheus.yml:/root/config/prometheus.yml
      - ./dashboards:/root/config/dashboards
      - ./.data/signoz/:/var/lib/signoz/

    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - STORAGE=clickhouse
      - POSTHOG_API_KEY=H-htDCae7CR3RV57gUzmol6IAKtm5IMCvbcm_fwnL-w
      - GODEBUG=netdns=go

    depends_on:
      clickhouse:
        condition: service_healthy

    networks:
      - default
      - shared-network

  frontend:
    image: signoz/frontend:0.5.0
    container_name: frontend

    depends_on:
      - query-service
    links:
      - "query-service"
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  shared-network:
    external: true
