version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data/lib:/var/lib/grafana
      - ./grafana/data/log:/var/log/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  agent:
    image: grafana/agent:v0.18.2
    command: [ "-config.file=/etc/agent.yml" ]
    volumes:
      - ./grafana/agent.yml:/etc/agent.yml

  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # for zPages
    volumes:
      - ./grafana/otel-collector.yml:/etc/otel-collector/config.yml
    command:
      - --config=/etc/otel-collector/config.yml
    networks:
      - default
      - shared-network

  tempo:
    container_name: tempo
    image: grafana/tempo:main-1899be3-arm64
    ports:
      - "14268" # jaeger ingest
      - "3200" # tempo
      - "55680" # otlp grpc
      - "55681" # otlp http
      - "9411" # zipkin
    volumes:
      - ./grafana/tempo.yml:/etc/tempo.yml
      - ./grafana/data/tempo:/tmp/tempo
    command:
      - "-config.file=/etc/tempo.yml"

  tempo-query:
    image: grafana/tempo-query:latest
    command:
      - "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yml"
    volumes:
      - ./grafana/tempo-query.yml:/etc/tempo-query.yml
    ports:
      - "16686:16686" # jaeger-ui
    depends_on:
      - tempo

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.31.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.grafana.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

networks:
  shared-network:
    external: true
