version: '3'
services:
  app:
    init: true
    build:
      context: .
      target: runtime
    container_name: app
    environment:
      - ASPNETCORE_URLS=http://+:5000;
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
      - MYSQL_SERVER_HOST=app_db
      - MYSQL_SERVER_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - OTLP_SERVER_NAME=dotnet-metric
      - OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - default
      - shared-network
    logging:
      driver: loki
      options:
        loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'

  app_web:
    container_name: web
    image: nginx:1.21.4-alpine
    volumes:
      - ./webserver/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - default
      - shared-network

  app_db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=
    #mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

  workspace:
    container_name: workspace
    build:
      context: .
      target: workspace
    tty: true
    networks:
      - default
      - shared-network
    volumes:
      - ./dotnet-metric-test:/source
    working_dir: /source

networks:
  shared-network:
    external: true
