version: '3'
services:
  app:
    build: ./dotnet-metric-test
    tty: true
    working_dir: /source
    ports:
      # for https
      - 7253:7253
      # for http
      - 5176:5176
    volumes:
      - ./dotnet-metric-test:/source
  db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
  prometheus:
    image: prom/prometheus:v2.31.1
  grafana:
    image: grafana/grafana:8.2.5
