version: '3'
services:
  app:
    build:
      context: ./dotnet-metric-test
      target: runtime
    environment:
      - ASPNETCORE_URLS=http://+:5000;
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
    networks:
      - default
      - shared-network

  app_web:
    image: nginx:1.21.4-alpine
    volumes:
      - ./webserver/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - default
      - shared-network

  app_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=
    #mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

  workspace:
    build:
      context: ./dotnet-metric-test
      target: workspace
    tty: true
    working_dir: /source
    volumes:
      - ./dotnet-metric-test:/source
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
