version: '3'
services:
  app:
    build: ./dotnet-metric-test
    tty: true
    working_dir: /source
    volumes:
      - ./dotnet-metric-test:/source
  app_web:
    image: nginx:1.21.4-alpine
    volumes:
      - ./webserver/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - 8080:80
    depends_on:
      - app
  app_db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
  metric_prometheus:
    image: prom/prometheus:v2.31.1
  metric_grafana:
    image: grafana/grafana:8.2.5
