version: '3'
services:
  app:
    build:
      context: .
      target: runtime
    container_name: app
    environment:
      - ASPNETCORE_URLS=http://+:5000;
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
    networks:
      - default
      - shared-network
    logging:
      driver: loki
      options:
        loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'

  app_web:
    container_name: web
    image: nginx:1.21.4-alpine
    volumes:
      - ./webserver/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - default
      - shared-network

  app_db:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=
    volumes:
      - ./sample/test_db/employees.sql:/docker-entrypoint-initdb.d/employees.sql
      - ./sample/test_db/load_departments.dump:/load_departments.dump
      - ./sample/test_db/load_employees.dump:/load_employees.dump
      - ./sample/test_db/load_dept_emp.dump:/load_dept_emp.dump
      - ./sample/test_db/load_dept_manager.dump:/load_dept_manager.dump
      - ./sample/test_db/load_titles.dump:/load_titles.dump
      - ./sample/test_db/load_salaries1.dump:/load_salaries1.dump
      - ./sample/test_db/load_salaries2.dump:/load_salaries2.dump
      - ./sample/test_db/load_salaries3.dump:/load_salaries3.dump
      - ./sample/test_db/show_elapsed.sql:/show_elapsed.sql
    #mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

  workspace:
    container_name: workspace
    build:
      context: .
      target: workspace
    tty: true
    networks:
      - default
      - shared-network
    volumes:
      - ./dotnet-metric-test:/source
    working_dir: /source

networks:
  shared-network:
    external: true
