server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system 
  pipeline_stages:
    - docker: {}
    - match:
        selector: '{compose_service="app"}'
        stages:
        - regex:
            expression: "(TraceId:\\s+(\\w+))|(traceId\\s+(\\w+))"
            traceID: traceID
        - labels:
            traceID:    
  static_configs:
    - labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*.log
