apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  namespace: cicd
  name: source-code-github
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/konnta0/dotnet-metric-test