version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.Controller
      target: runtime
    container_name: controller
    environment:
      - PORT_WEB=7312
      - PORT_WORKER=7313
    networks:
      - default
      - shared-network
  worker:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.Worker
      target: runtime
    container_name: worker
    environment:
      - ROOT_ADRESS="http://app/"
      - CONTROLLER_ADDRESS="http://controller:7313"
    networks:
      - default
      - shared-network
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.RestApi
      target: runtime
    container_name: rest-api
    environment:
      - CONTROLLER_ROOT_ADDRESS="http://controller:7312"
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
